[build]
  command = "npm run build"
  publish = "dist/dragon-ball/browser"

[[redirects]]
  from = "/api/*"
  to = "https://www.dragonball-api.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[trailingSlash]
  value = "never"